from django.urls import path
from . import views

urlpatterns = [
    path('speed_convert/',views.speed_convert,name = 'speed_convert'),
    path('kineticfriction/',views.kineticfriction,name = 'kineticfriction'),
    path('instantaneous_velocity/',views.instantaneous_velocity,name = 'instantaneous_velocity/'),
    path('horsepower/',views.horsepower,name= 'horsepower'),
    path('impulse/',views.impulse,name = 'impulse'),
    path('inductivereactance/',views.inductivereactance,name = 'inductivereactance'),
    path('heattransfer/',views.heattransfer,name = 'heattransfer'),
    path('machnumber/',views.machnumber,name = 'machnumber'),
    path('lcresonance/',views.lcresonance,name = 'lcresonance'),
    path('zenerdiode/',views.zenerdiode,name = 'zenerdiode'),
    path('centripetal_acceleration/',views.centripetal_acceleration,name='centripetal_acceleration'),
    path('resistance_frequency_capacitance/',views.resistance_frequency_capacitance,name =  'resistance_frequency_capacitance'),
    path('kinematic/',views.kinematic,name = 'kinematic'),
    path('voltageresistancepowercurrent/',views.voltageresistancepowercurrent,name = 'voltageresistancepowercurrent'),
    path('specificheatanddensity/',views.specificheatanddensity,name = 'specificheatanddensity'),
    path('roundone/',views.roundone,name = 'roundone'),
    path('roundtotwo/',views.roundtotwo,name = 'roundtotwo'),
    path('roundtothree/',views.roundtothree,name = 'roundtothree'),
    path('sigfig/',views.sigfig, name = 'sigfig'),
    path('time_clock_15_minutes/',views.time_clock_15_minutes,name = 'time_clock_15_minutes'),
    path('nearest_eighth/',views.nearest_eighth,name = 'nearest_eighth'),
    path('identifying_perfect_cube/',views.identifying_perfect_cube,name = 'identifying_perfect_cube'),
    path('cancel_out/',views.cancel_out,name = 'cancel_out'),
    path('feet_inch/',views.feet_inch,name = 'feet_inch'),
    path('nearest_feet/',views.nearest_feet,name = 'nearest_feet'),
    path('meter_centimeter/',views.meter_centimeter,name = 'meter_centimeter'),
    path('nearest_meter/',views.nearest_meter,name = 'nearest_meter'),
    path('centimeter_millimeter/',views.centimeter_millimeter,name = 'centimeter_millimeter'),
    path('nearest_centimeter/',views.nearest_centimeter,name = 'nearest_centimeter'),
    path('kilometer_meter/',views.kilometer_meter,name = 'kilometer_meter'),
    path('nearest_kilometer/',views.nearest_kilometer,name = 'nearest_kilometer'),
    path('nearest_millimeter/',views.nearest_millimeter,name = 'nearest_millimeter'),
    path('millimeter_micrometer/',views.millimeter_micrometer,name = 'millimeter_micrometer'),
    path('nearest_micrometer/',views.nearest_micrometer,name = 'nearest_micrometer'),
    path('micrometer_nanometer/',views.micrometer_nanometer,name = 'micrometer_nanometer'),
    path('nearest_nanometer/',views.nearest_nanometer,name = 'nearest_nanometer'),
    path('nearest_yard/',views.nearest_yard,name = 'nearest_yard'),
    path('nearest_mile/',views.nearest_mile,name = 'nearest_mile'),
    path('time_clock_30_minutes/',views.time_clock_30_minutes,name = 'time_clock_30_minutes')

]